name = "x402-dev"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

# Default (development) configuration
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"

# Staging environment
[env.staging]
name = "x402-dev-staging"
vars = { ENVIRONMENT = "staging", LOG_LEVEL = "info" }
route = { pattern = "x402-dev-staging.workers.dev", custom_domain = false }

# Production environment
[env.production]
name = "x402-dev-production"
vars = { ENVIRONMENT = "production", LOG_LEVEL = "warn" }
route = { pattern = "x402.dev", custom_domain = true }

# KV Namespaces (uncomment when needed)
# [[kv_namespaces]]
# binding = "X402_KV"
# id = "your-kv-namespace-id"
# 
# [env.staging.kv_namespaces]
# binding = "X402_KV"
# id = "your-staging-kv-namespace-id"
# 
# [env.production.kv_namespaces]
# binding = "X402_KV"
# id = "your-production-kv-namespace-id"

# Durable Objects (uncomment when needed)
# [[durable_objects.bindings]]
# name = "X402_DO"
# class_name = "X402DurableObject"

# R2 Buckets (uncomment when needed)
# [[r2_buckets]]
# binding = "X402_BUCKET"
# bucket_name = "x402-storage"
# 
# [env.staging.r2_buckets]
# binding = "X402_BUCKET"
# bucket_name = "x402-storage-staging"
# 
# [env.production.r2_buckets]
# binding = "X402_BUCKET"
# bucket_name = "x402-storage-production"

# Analytics Engine (uncomment when needed)
# [[analytics_engine_datasets]]
# binding = "X402_ANALYTICS"

# Build configuration
[build]
command = "npm run build"

[build.upload]
format = "service-worker"
